import type { AppState } from './model';

export const initialState: AppState = {
  projects: [],
  sessions: [],
  activeProjectId: null,
  activeSessionId: null,
  connectionStatus: 'checking',
  connectionDetail: '正在检查本机 Grok Build…',
  connectionAttemptId: 0,
  connectionIssueCode: null,
  connectionRetryable: false,
  grokBinaryPath: null,
  grokCliVersion: null,
  grokAuthenticated: null,
  grokAuthMethod: null,
  grokLogoutSupported: false,
  grokAgentName: null,
  grokAgentVersion: null,
  draftsBySessionId: {},
  autoConnectGrok: true,
  uiTextScale: 'large',
  pendingPermissions: [],
  sidebarCollapsed: false,
  inspectorOpen: false,
  inspectorTab: 'changes',
  commandPaletteOpen: false,
  settingsOpen: false,
  appVersion: '0.2.0-alpha.5',
  appPlatform: 'darwin',
  appArch: 'arm64',
};
